# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 678cd65cc3da7e395b273509f5c4857dfa4e6d725378af945a22bb7e22c52508e808e7ea4bf2ab205ffbe36903392d8a0488c5fcd6d1e8b7907d03147bb6b6f6

test:
  secret_key_base: ab0a1e53d5ea5c06bc2f72095c766de625a2a84f9d31643e8430e2025c72605d6d6b5bef9ba6febbc28d81e594511603a313d359d5f3a546b5dd34e2cd1e3c14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
